version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_1803Project
  gitServerName: SIQA_KVV_IBM
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: TPP_services_in_FCS
  version: "1.0"
  gitServerName: SIQA_KVV_IBM
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.siqa_1803.integrations:AlertsCRTandERT
  packages:
  - name: SIQA_1803Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 11.1.0.0.2039
- serviceName: project.siqa_1803.integrations:JMS_JNDI_SSL
  packages:
  - name: SIQA_1803Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: publisher:publisher
  packages:
  - name: JMSTest
    version: "1.0"
- serviceName: pub.jms:send
  packages:
  - name: WmPublic
    version: 11.1.0.0.2039
- serviceName: project.siqa_1803.integrations:Sum
  packages:
  - name: SIQA_1803Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2039
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2039
- serviceName: project.siqa_1803.integrations:deepclonetest
  packages:
  - name: SIQA_1803Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2039
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2039
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2039
- serviceName: project.siqa_1803.integrations:tppdaf
  packages:
  - name: SIQA_1803Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: services:add3Ints
  packages:
  - name: TPP_services_in_FCS
    version: "1.0"
